### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'bot' of undefined

### ISSUE THREAD

**Issue by naresh89** [johnagan/servicenow-bot-example#1]
Steps to reproduce:
--------------------------------
1. Created OAUTH on Slack and ServiceNow
2. Updated all Environment Variables
3. Created Slack side integration with the help of 'Slash commands'.
4. Updated the Slack URL to the NodeJs application running in my local.

When I enter '/incidents create test-ticket' , It is hitting my app running locally.And seeing the error as below in the log.

Stack Trace:

> SampleAppBot@1.0.0 start /home/Slack/sampleAppBot
> node index.js

Server Started
Express server   listening on port 3002 in development mode
(node:1241) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'bot' of undefined
(node:1241) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I tried couple error handling ways for Promise but don't see it off.Any inputs to progress on this??

Thanks

**Comment by johnagan** [comment]
Did you authenticate the app to get a token? The error sounds like it didn't find the token.

**Comment by pariminaresh** [comment]
Ok. Thank You John.
Trying to figure out what went wrong.
1.I configured the client_id, client_secret & verification token values from the installed Slack app and registered the Oauth redirect URL as http://myapp.com/slack.
2.Scope as bot,commands - Created a bot user and configured a slash command

Am I missing anything here or need to correct any config.

**Comment by johnagan** [comment]
@pariminaresh try following that url once and authorize your app. Check out the [Slack OAuth flow](https://github.com/johnagan/servicenow-bot-example#prerequisites)
