### ISSUE TITLE
Just a slack query about permission

### ISSUE THREAD

**Issue by ravi100k** [johnagan/servicenow-bot-example#3]
I just wanted to know what are the permission I have to provide to get this code working.

I have configured a slack bot current I am just listening to the im.message event.

**And what are the "Select Permission Scopes" and "Event Subscriptions" configuration?**

Thanks in advance.

**Comment by johnagan** [comment]
It depends on what events you subscribe to. When you select the event, Slack will auto include the related scopes

**Comment by ravi100k** [comment]
so what is the event I have to subscribe to this chatbot?
